# Shell variables
# Generated by 'wal'
wallpaper='/home/rei/Pictures/wallpaper/ZpfA7d2W_4x.jpg'

# Special
background='#151315'
foreground='#e8e8e4'
cursor='#e8e8e4'

# Colors
color0='#151315'
color1='#3B5DA4'
color2='#943A9C'
color3='#2CB2C9'
color4='#F19893'
color5='#DECCB7'
color6='#A8C0C6'
color7='#e8e8e4'
color8='#a2a29f'
color9='#3B5DA4'
color10='#943A9C'
color11='#2CB2C9'
color12='#F19893'
color13='#DECCB7'
color14='#A8C0C6'
color15='#e8e8e4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
