--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rei/Pictures/wallpaper/ZpfA7d2W_4x.jpg"

-- Special
background="#151315"
foreground="#e8e8e4"
cursor="#e8e8e4"

-- Colors
color0="#151315"
color1="#3B5DA4"
color2="#943A9C"
color3="#2CB2C9"
color4="#F19893"
color5="#DECCB7"
color6="#A8C0C6"
color7="#e8e8e4"
color8="#a2a29f"
color9="#3B5DA4"
color10="#943A9C"
color11="#2CB2C9"
color12="#F19893"
color13="#DECCB7"
color14="#A8C0C6"
color15="#e8e8e4"
