--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rei/wallpapers/wallpaper.jpg"

-- Special
background="#01050C"
foreground="#dee9cd"
cursor="#dee9cd"

-- Colors
color0="#01050C"
color1="#B2DA6F"
color2="#BAE278"
color3="#444A86"
color4="#B9DC85"
color5="#BCE485"
color6="#C6EA8E"
color7="#dee9cd"
color8="#9ba38f"
color9="#B2DA6F"
color10="#BAE278"
color11="#444A86"
color12="#B9DC85"
color13="#BCE485"
color14="#C6EA8E"
color15="#dee9cd"
