# Shell variables
# Generated by 'wal'
wallpaper='/home/rei/wallpapers/wallpaper.jpg'

# Special
background='#01050C'
foreground='#dee9cd'
cursor='#dee9cd'

# Colors
color0='#01050C'
color1='#B2DA6F'
color2='#BAE278'
color3='#444A86'
color4='#B9DC85'
color5='#BCE485'
color6='#C6EA8E'
color7='#dee9cd'
color8='#9ba38f'
color9='#B2DA6F'
color10='#BAE278'
color11='#444A86'
color12='#B9DC85'
color13='#BCE485'
color14='#C6EA8E'
color15='#dee9cd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
