--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/gamer/Pictures/wallpapers/wbnn4jk6p9j31.jpg"

-- Special
background="#181c14"
foreground="#cbdbf0"
cursor="#cbdbf0"

-- Colors
color0="#181c14"
color1="#8ABB0C"
color2="#3B54A9"
color3="#1C70EF"
color4="#3E84ED"
color5="#649CF2"
color6="#90B5F2"
color7="#cbdbf0"
color8="#8e99a8"
color9="#8ABB0C"
color10="#3B54A9"
color11="#1C70EF"
color12="#3E84ED"
color13="#649CF2"
color14="#90B5F2"
color15="#cbdbf0"
