# Shell variables
# Generated by 'wal'
wallpaper='/home/gamer/Pictures/wallpapers/wbnn4jk6p9j31.jpg'

# Special
background='#181c14'
foreground='#cbdbf0'
cursor='#cbdbf0'

# Colors
color0='#181c14'
color1='#8ABB0C'
color2='#3B54A9'
color3='#1C70EF'
color4='#3E84ED'
color5='#649CF2'
color6='#90B5F2'
color7='#cbdbf0'
color8='#8e99a8'
color9='#8ABB0C'
color10='#3B54A9'
color11='#1C70EF'
color12='#3E84ED'
color13='#649CF2'
color14='#90B5F2'
color15='#cbdbf0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
