--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rei/Pictures/wallpaper/xVWaGv3.jpg"

-- Special
background="#0e0f1e"
foreground="#85c4e6"
cursor="#85c4e6"

-- Colors
color0="#0e0f1e"
color1="#B02354"
color2="#063589"
color3="#2D328D"
color4="#0A51A1"
color5="#4550A9"
color6="#AD5E98"
color7="#85c4e6"
color8="#5d89a1"
color9="#B02354"
color10="#063589"
color11="#2D328D"
color12="#0A51A1"
color13="#4550A9"
color14="#AD5E98"
color15="#85c4e6"
