--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/gamer/Pictures/2022-02-07_20-12.png"

-- Special
background="#150f0f"
foreground="#cfc4bf"
cursor="#cfc4bf"

-- Colors
color0="#150f0f"
color1="#76675D"
color2="#857D39"
color3="#8E7166"
color4="#97903B"
color5="#A18777"
color6="#847A85"
color7="#cfc4bf"
color8="#908985"
color9="#76675D"
color10="#857D39"
color11="#8E7166"
color12="#97903B"
color13="#A18777"
color14="#847A85"
color15="#cfc4bf"
