# Shell variables
# Generated by 'wal'
wallpaper='/home/gamer/Pictures/2022-02-07_20-12.png'

# Special
background='#150f0f'
foreground='#cfc4bf'
cursor='#cfc4bf'

# Colors
color0='#150f0f'
color1='#76675D'
color2='#857D39'
color3='#8E7166'
color4='#97903B'
color5='#A18777'
color6='#847A85'
color7='#cfc4bf'
color8='#908985'
color9='#76675D'
color10='#857D39'
color11='#8E7166'
color12='#97903B'
color13='#A18777'
color14='#847A85'
color15='#cfc4bf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
