--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rei/wallpaper/rain.jpg"

-- Special
background="#0e090b"
foreground="#b9b8bb"
cursor="#b9b8bb"

-- Colors
color0="#0e090b"
color1="#6E2D2B"
color2="#4A3E43"
color3="#62555C"
color4="#962925"
color5="#EF322A"
color6="#B35850"
color7="#b9b8bb"
color8="#818082"
color9="#6E2D2B"
color10="#4A3E43"
color11="#62555C"
color12="#962925"
color13="#EF322A"
color14="#B35850"
color15="#b9b8bb"
