--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rei/Pictures/wallpaper/light_floral_highres_everforest.png"

-- Special
background="#0a1116"
foreground="#e3dcd2"
cursor="#e3dcd2"

-- Colors
color0="#0a1116"
color1="#906F65"
color2="#7B8479"
color3="#8C877A"
color4="#D28B77"
color5="#A39E90"
color6="#C8B8A5"
color7="#e3dcd2"
color8="#9e9a93"
color9="#906F65"
color10="#7B8479"
color11="#8C877A"
color12="#D28B77"
color13="#A39E90"
color14="#C8B8A5"
color15="#e3dcd2"
