--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rei/pictures/wallpaper/2560x1440-987220-anime-manga-anime-girls-simple-background-minimalism.png"

-- Special
background="#3f2728"
foreground="#efe7e6"
cursor="#efe7e6"

-- Colors
color0="#3f2728"
color1="#E8B7B6"
color2="#D8C4BA"
color3="#E6C2BD"
color4="#EABEC2"
color5="#DCD3CB"
color6="#E9CDCC"
color7="#efe7e6"
color8="#a7a1a1"
color9="#E8B7B6"
color10="#D8C4BA"
color11="#E6C2BD"
color12="#EABEC2"
color13="#DCD3CB"
color14="#E9CDCC"
color15="#efe7e6"
