# Shell variables
# Generated by 'wal'
wallpaper='/home/rei/pictures/wallpaper/2560x1440-987220-anime-manga-anime-girls-simple-background-minimalism.png'

# Special
background='#3f2728'
foreground='#efe7e6'
cursor='#efe7e6'

# Colors
color0='#3f2728'
color1='#E8B7B6'
color2='#D8C4BA'
color3='#E6C2BD'
color4='#EABEC2'
color5='#DCD3CB'
color6='#E9CDCC'
color7='#efe7e6'
color8='#a7a1a1'
color9='#E8B7B6'
color10='#D8C4BA'
color11='#E6C2BD'
color12='#EABEC2'
color13='#DCD3CB'
color14='#E9CDCC'
color15='#efe7e6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
